apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-api
  namespace: mayabank-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-api
  template:
    metadata:
      labels:
        app: payment-api
    spec:
      containers:
        - name: api
          image: quay.io/placeholder/mayabank-payment-api:lab
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment-api
  namespace: mayabank-api
spec:
  selector:
    app: payment-api
  ports:
    - port: 8080
      targetPort: 8080
